name: testseite
favicon: null
layout_spectrum: 0.73623
typography_spectrum: 0.0636
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ededed'
    - '#98c4d3'
    - '#598b9f'
    - '#c88966'
    - '#3d3c42'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
