name: testseite
favicon: null
layout_spectrum: 0.99537
typography_spectrum: 0.1088
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#009de0'
    - '#f3f3f3'
    - '#580000'
    - '#fb4200'
    - '#9e7d20'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
