name: testseite
favicon: null
layout_spectrum: 0.22225
typography_spectrum: 0.8786536552943289
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#f2ac00'
    - '#005397'
    - '#83c025'
    - '#8b8b8b'
  brandStrength: 0.7389637345913798
  lightness: 0.1265133915003389
  saturation: 0.9346148443873972
  rhythmicContrast: 0.9962459767702967
purpose: []
