name: testseite
favicon: null
layout_spectrum: 0.22225
typography_spectrum: 0.0636
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ec7a00'
    - '#fde7d1'
    - '#fda231'
    - '#fdca91'
  brandStrength: 0.7389637345913798
  lightness: 0.1265133915003389
  saturation: 0.9346148443873972
  rhythmicContrast: 0.9962459767702967
purpose: []
